context:
  version: "3.5.4"

package:
  name: libmseed
  version: ${{ version }}

source:
  url: https://github.com/EarthScope/libmseed/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f397b9a32714164d6440b9eeadfbf5b4aece46184515b6ba48941e2cbcb4806a

build:
  number: 1
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - libcurl
  run_exports:
    - ${{ pin_subpackage('libmseed', upper_bound='x.x.x') }}

tests:
  - package_contents:
      include:
        - libmseed.h
        - mseedformat.h
      lib:
        - mseed

about:
  homepage: https://github.com/EarthScope/libmseed
  summary: C library for reading, writing, and handling miniSEED data
  description: |
    libmseed is a C library for reading, writing, and handling miniSEED
    formatted time series data. miniSEED is a ubiquitous format used in
    seismological data archiving and distribution.
  license: Apache-2.0
  license_file: LICENSE
  repository: https://github.com/EarthScope/libmseed

extra:
  recipe-maintainers:
    - omid-earthscope
